// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, owner_id, start_date, turn_length_days)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, created_at, start_date, turn_length_days
`

type CreateGroupParams struct {
	Name           string      `json:"name"`
	OwnerID        int32       `json:"owner_id"`
	StartDate      pgtype.Date `json:"start_date"`
	TurnLengthDays int32       `json:"turn_length_days"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.OwnerID,
		arg.StartDate,
		arg.TurnLengthDays,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.StartDate,
		&i.TurnLengthDays,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, group_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, group_id, role, joined_at
`

type CreateMembershipParams struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	Role    string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.GroupID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND group_id = $2
`

type DeleteMembershipParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.GroupID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, owner_id, created_at, start_date, turn_length_days
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.StartDate,
		&i.TurnLengthDays,
	)
	return i, err
}

const getGroupMemberCount = `-- name: GetGroupMemberCount :one
SELECT COUNT(*) AS count FROM memberships WHERE group_id = $1
`

func (q *Queries) GetGroupMemberCount(ctx context.Context, groupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getGroupMemberCount, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT m.id, m.user_id, m.group_id, m.role, m.joined_at, u.username, u.avatar_url
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1
ORDER BY m.joined_at
`

type GetGroupMembersRow struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	GroupID   int32     `json:"group_id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
	Username  string    `json:"username"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID int32) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, group_id, role, joined_at
FROM memberships
WHERE user_id = $1 AND group_id = $2
`

type GetMembershipParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.GroupID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.owner_id, g.created_at, g.start_date, g.turn_length_days,
       m.role,
       (SELECT COUNT(*) FROM memberships WHERE group_id = g.id) AS member_count
FROM groups g
JOIN memberships m ON m.group_id = g.id
WHERE m.user_id = $1
ORDER BY g.created_at DESC
`

type GetUserGroupsRow struct {
	ID             int32       `json:"id"`
	Name           string      `json:"name"`
	OwnerID        int32       `json:"owner_id"`
	CreatedAt      time.Time   `json:"created_at"`
	StartDate      pgtype.Date `json:"start_date"`
	TurnLengthDays int32       `json:"turn_length_days"`
	Role           string      `json:"role"`
	MemberCount    int64       `json:"member_count"`
}

func (q *Queries) GetUserGroups(ctx context.Context, userID int32) ([]GetUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupsRow{}
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.StartDate,
			&i.TurnLengthDays,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupOwner = `-- name: UpdateGroupOwner :exec
UPDATE groups SET owner_id = $2 WHERE id = $1
`

type UpdateGroupOwnerParams struct {
	ID      int32 `json:"id"`
	OwnerID int32 `json:"owner_id"`
}

func (q *Queries) UpdateGroupOwner(ctx context.Context, arg UpdateGroupOwnerParams) error {
	_, err := q.db.Exec(ctx, updateGroupOwner, arg.ID, arg.OwnerID)
	return err
}

const updateGroupSettings = `-- name: UpdateGroupSettings :one
UPDATE groups
SET start_date = COALESCE($2, start_date),
    turn_length_days = COALESCE($3, turn_length_days)
WHERE id = $1
RETURNING id, name, owner_id, created_at, start_date, turn_length_days
`

type UpdateGroupSettingsParams struct {
	ID             int32       `json:"id"`
	StartDate      pgtype.Date `json:"start_date"`
	TurnLengthDays int32       `json:"turn_length_days"`
}

func (q *Queries) UpdateGroupSettings(ctx context.Context, arg UpdateGroupSettingsParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupSettings, arg.ID, arg.StartDate, arg.TurnLengthDays)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.StartDate,
		&i.TurnLengthDays,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE memberships SET role = $3 WHERE user_id = $1 AND group_id = $2
`

type UpdateMemberRoleParams struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	Role    string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.UserID, arg.GroupID, arg.Role)
	return err
}
