// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Film struct {
	ID             int64              `json:"id"`
	ImdbID         string             `json:"imdb_id"`
	Title          string             `json:"title"`
	Year           *int32             `json:"year"`
	PosterUrl      *string            `json:"poster_url"`
	Director       *string            `json:"director"`
	Genre          *string            `json:"genre"`
	RuntimeMinutes *int32             `json:"runtime_minutes"`
	OmdbFetchedAt  pgtype.Timestamptz `json:"omdb_fetched_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID             int32       `json:"id"`
	Name           string      `json:"name"`
	OwnerID        int32       `json:"owner_id"`
	CreatedAt      time.Time   `json:"created_at"`
	StartDate      pgtype.Date `json:"start_date"`
	TurnLengthDays int32       `json:"turn_length_days"`
}

type Invite struct {
	ID              int32      `json:"id"`
	Code            string     `json:"code"`
	GroupID         int32      `json:"group_id"`
	CreatedByUserID int32      `json:"created_by_user_id"`
	ExpiresAt       *time.Time `json:"expires_at"`
	CreatedAt       time.Time  `json:"created_at"`
}

type Membership struct {
	ID       int32     `json:"id"`
	UserID   int32     `json:"user_id"`
	GroupID  int32     `json:"group_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type Movie struct {
	ID              int32     `json:"id"`
	GroupID         int32     `json:"group_id"`
	NominatorUserID *int32    `json:"nominator_user_id"`
	CreatedAt       time.Time `json:"created_at"`
	FilmID          int64     `json:"film_id"`
	TurnID          int64     `json:"turn_id"`
}

type Nomination struct {
	ID        int32     `json:"id"`
	GroupID   int32     `json:"group_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	FilmID    int64     `json:"film_id"`
}

type Reaction struct {
	ID         int64              `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	UserID     int32              `json:"user_id"`
	StickerID  int64              `json:"sticker_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Sticker struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	ImageUrl  string             `json:"image_url"`
	GroupID   *int64             `json:"group_id"`
	CreatedBy int32              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Turn struct {
	ID              int64              `json:"id"`
	GroupID         int32              `json:"group_id"`
	TurnIndex       int32              `json:"turn_index"`
	WeekOf          pgtype.Date        `json:"week_of"`
	PickerUserID    int32              `json:"picker_user_id"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	MovieUnlocked   bool               `json:"movie_unlocked"`
	ReviewsUnlocked bool               `json:"reviews_unlocked"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  int32     `json:"id"`
	Username            string    `json:"username"`
	PasswordHash        *string   `json:"password_hash"`
	CreatedAt           time.Time `json:"created_at"`
	AvatarUrl           *string   `json:"avatar_url"`
	LetterboxdUsername  *string   `json:"letterboxd_username"`
	MovieLinkPreference string    `json:"movie_link_preference"`
}

type Verdict struct {
	ID        int64              `json:"id"`
	TurnID    int64              `json:"turn_id"`
	UserID    int32              `json:"user_id"`
	Watched   bool               `json:"watched"`
	Rating    pgtype.Numeric     `json:"rating"`
	Review    *string            `json:"review"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
