// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSharedClubMembership = `-- name: CheckSharedClubMembership :one
SELECT EXISTS (
    SELECT 1 FROM memberships m1
    JOIN memberships m2 ON m1.group_id = m2.group_id
    WHERE m1.user_id = $1 AND m2.user_id = $2
) AS shared
`

type CheckSharedClubMembershipParams struct {
	UserID   int32 `json:"user_id"`
	UserID_2 int32 `json:"user_id_2"`
}

func (q *Queries) CheckSharedClubMembership(ctx context.Context, arg CheckSharedClubMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSharedClubMembership, arg.UserID, arg.UserID_2)
	var shared bool
	err := row.Scan(&shared)
	return shared, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, username, avatar_url, letterboxd_username, created_at
FROM users
WHERE id = $1
`

type GetUserProfileRow struct {
	ID                 int32     `json:"id"`
	Username           string    `json:"username"`
	AvatarUrl          *string   `json:"avatar_url"`
	LetterboxdUsername *string   `json:"letterboxd_username"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id int32) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.LetterboxdUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRecentActivity = `-- name: GetUserRecentActivity :many
SELECT
    f.id AS film_id,
    f.title,
    f.year,
    f.poster_url,
    v.rating,
    v.review,
    v.updated_at AS watched_at
FROM verdicts v
JOIN turns t ON v.turn_id = t.id
JOIN movies m ON m.turn_id = t.id
JOIN films f ON m.film_id = f.id
WHERE v.user_id = $1 AND v.watched = true
ORDER BY v.updated_at DESC
LIMIT 10
`

type GetUserRecentActivityRow struct {
	FilmID    int64              `json:"film_id"`
	Title     string             `json:"title"`
	Year      *int32             `json:"year"`
	PosterUrl *string            `json:"poster_url"`
	Rating    pgtype.Numeric     `json:"rating"`
	Review    *string            `json:"review"`
	WatchedAt pgtype.Timestamptz `json:"watched_at"`
}

func (q *Queries) GetUserRecentActivity(ctx context.Context, userID int32) ([]GetUserRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRecentActivityRow{}
	for rows.Next() {
		var i GetUserRecentActivityRow
		if err := rows.Scan(
			&i.FilmID,
			&i.Title,
			&i.Year,
			&i.PosterUrl,
			&i.Rating,
			&i.Review,
			&i.WatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecentActivityForViewer = `-- name: GetUserRecentActivityForViewer :many
SELECT
    f.id AS film_id,
    f.title,
    f.year,
    f.poster_url,
    v.rating,
    v.review,
    v.updated_at AS watched_at
FROM verdicts v
JOIN turns t ON v.turn_id = t.id
JOIN movies m ON m.turn_id = t.id
JOIN films f ON m.film_id = f.id
WHERE v.user_id = $1
  AND v.watched = true
  AND t.group_id IN (
      SELECT m1.group_id FROM memberships m1
      JOIN memberships m2 ON m1.group_id = m2.group_id
      WHERE m1.user_id = $1 AND m2.user_id = $2
  )
ORDER BY v.updated_at DESC
LIMIT 10
`

type GetUserRecentActivityForViewerParams struct {
	UserID   int32 `json:"user_id"`
	UserID_2 int32 `json:"user_id_2"`
}

type GetUserRecentActivityForViewerRow struct {
	FilmID    int64              `json:"film_id"`
	Title     string             `json:"title"`
	Year      *int32             `json:"year"`
	PosterUrl *string            `json:"poster_url"`
	Rating    pgtype.Numeric     `json:"rating"`
	Review    *string            `json:"review"`
	WatchedAt pgtype.Timestamptz `json:"watched_at"`
}

// Only returns activity from clubs shared between viewer and target user
func (q *Queries) GetUserRecentActivityForViewer(ctx context.Context, arg GetUserRecentActivityForViewerParams) ([]GetUserRecentActivityForViewerRow, error) {
	rows, err := q.db.Query(ctx, getUserRecentActivityForViewer, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRecentActivityForViewerRow{}
	for rows.Next() {
		var i GetUserRecentActivityForViewerRow
		if err := rows.Scan(
			&i.FilmID,
			&i.Title,
			&i.Year,
			&i.PosterUrl,
			&i.Rating,
			&i.Review,
			&i.WatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COALESCE(AVG(rating)::numeric(3,2), 0) AS avg_rating,
    COUNT(*) FILTER (WHERE watched = true) AS total_watched,
    COUNT(*) FILTER (WHERE review IS NOT NULL AND review != '') AS total_reviews
FROM verdicts
WHERE user_id = $1
`

type GetUserStatsRow struct {
	AvgRating    interface{} `json:"avg_rating"`
	TotalWatched int64       `json:"total_watched"`
	TotalReviews int64       `json:"total_reviews"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID int32) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.AvgRating, &i.TotalWatched, &i.TotalReviews)
	return i, err
}

const getUserTopGenres = `-- name: GetUserTopGenres :many
SELECT f.genre, COUNT(*) AS cnt
FROM verdicts v
JOIN turns t ON v.turn_id = t.id
JOIN movies m ON m.turn_id = t.id
JOIN films f ON m.film_id = f.id
WHERE v.user_id = $1 AND v.watched = true AND f.genre IS NOT NULL
GROUP BY f.genre
ORDER BY cnt DESC
LIMIT 5
`

type GetUserTopGenresRow struct {
	Genre *string `json:"genre"`
	Cnt   int64   `json:"cnt"`
}

func (q *Queries) GetUserTopGenres(ctx context.Context, userID int32) ([]GetUserTopGenresRow, error) {
	rows, err := q.db.Query(ctx, getUserTopGenres, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTopGenresRow{}
	for rows.Next() {
		var i GetUserTopGenresRow
		if err := rows.Scan(&i.Genre, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLetterboxdUsername = `-- name: UpdateLetterboxdUsername :one
UPDATE users
SET letterboxd_username = $2
WHERE id = $1
RETURNING id, username, avatar_url, letterboxd_username, created_at
`

type UpdateLetterboxdUsernameParams struct {
	ID                 int32   `json:"id"`
	LetterboxdUsername *string `json:"letterboxd_username"`
}

type UpdateLetterboxdUsernameRow struct {
	ID                 int32     `json:"id"`
	Username           string    `json:"username"`
	AvatarUrl          *string   `json:"avatar_url"`
	LetterboxdUsername *string   `json:"letterboxd_username"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) UpdateLetterboxdUsername(ctx context.Context, arg UpdateLetterboxdUsernameParams) (UpdateLetterboxdUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateLetterboxdUsername, arg.ID, arg.LetterboxdUsername)
	var i UpdateLetterboxdUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.LetterboxdUsername,
		&i.CreatedAt,
	)
	return i, err
}
