// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReaction = `-- name: CreateReaction :one
INSERT INTO reactions (entity_type, entity_id, user_id, sticker_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT reactions_unique DO NOTHING
RETURNING id, entity_type, entity_id, user_id, sticker_id, created_at
`

type CreateReactionParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	UserID     int32  `json:"user_id"`
	StickerID  int64  `json:"sticker_id"`
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, createReaction,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.StickerID,
	)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.UserID,
		&i.StickerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions
WHERE id = $1
`

func (q *Queries) DeleteReaction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReaction, id)
	return err
}

const deleteReactionByUserAndSticker = `-- name: DeleteReactionByUserAndSticker :execrows
DELETE FROM reactions
WHERE entity_type = $1 AND entity_id = $2 AND user_id = $3 AND sticker_id = $4
`

type DeleteReactionByUserAndStickerParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	UserID     int32  `json:"user_id"`
	StickerID  int64  `json:"sticker_id"`
}

func (q *Queries) DeleteReactionByUserAndSticker(ctx context.Context, arg DeleteReactionByUserAndStickerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReactionByUserAndSticker,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.StickerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReactionsForEntity = `-- name: DeleteReactionsForEntity :exec
DELETE FROM reactions
WHERE entity_type = $1 AND entity_id = $2
`

type DeleteReactionsForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) DeleteReactionsForEntity(ctx context.Context, arg DeleteReactionsForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteReactionsForEntity, arg.EntityType, arg.EntityID)
	return err
}

const getReactionByID = `-- name: GetReactionByID :one
SELECT id, entity_type, entity_id, user_id, sticker_id, created_at
FROM reactions
WHERE id = $1
`

func (q *Queries) GetReactionByID(ctx context.Context, id int64) (Reaction, error) {
	row := q.db.QueryRow(ctx, getReactionByID, id)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.UserID,
		&i.StickerID,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionSummaryForEntity = `-- name: GetReactionSummaryForEntity :many
SELECT r.sticker_id, s.name AS sticker_name, s.image_url AS sticker_image_url,
       COUNT(*) AS count
FROM reactions r
JOIN stickers s ON s.id = r.sticker_id
WHERE r.entity_type = $1 AND r.entity_id = $2
GROUP BY r.sticker_id, s.name, s.image_url
ORDER BY count DESC
`

type GetReactionSummaryForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

type GetReactionSummaryForEntityRow struct {
	StickerID       int64  `json:"sticker_id"`
	StickerName     string `json:"sticker_name"`
	StickerImageUrl string `json:"sticker_image_url"`
	Count           int64  `json:"count"`
}

func (q *Queries) GetReactionSummaryForEntity(ctx context.Context, arg GetReactionSummaryForEntityParams) ([]GetReactionSummaryForEntityRow, error) {
	rows, err := q.db.Query(ctx, getReactionSummaryForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionSummaryForEntityRow{}
	for rows.Next() {
		var i GetReactionSummaryForEntityRow
		if err := rows.Scan(
			&i.StickerID,
			&i.StickerName,
			&i.StickerImageUrl,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionsForEntity = `-- name: GetReactionsForEntity :many
SELECT r.id, r.entity_type, r.entity_id, r.user_id, r.sticker_id, r.created_at,
       s.name AS sticker_name, s.image_url AS sticker_image_url,
       u.username, u.avatar_url
FROM reactions r
JOIN stickers s ON s.id = r.sticker_id
JOIN users u ON u.id = r.user_id
WHERE r.entity_type = $1 AND r.entity_id = $2
ORDER BY r.created_at
`

type GetReactionsForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

type GetReactionsForEntityRow struct {
	ID              int64              `json:"id"`
	EntityType      string             `json:"entity_type"`
	EntityID        int64              `json:"entity_id"`
	UserID          int32              `json:"user_id"`
	StickerID       int64              `json:"sticker_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StickerName     string             `json:"sticker_name"`
	StickerImageUrl string             `json:"sticker_image_url"`
	Username        string             `json:"username"`
	AvatarUrl       *string            `json:"avatar_url"`
}

func (q *Queries) GetReactionsForEntity(ctx context.Context, arg GetReactionsForEntityParams) ([]GetReactionsForEntityRow, error) {
	rows, err := q.db.Query(ctx, getReactionsForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionsForEntityRow{}
	for rows.Next() {
		var i GetReactionsForEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.UserID,
			&i.StickerID,
			&i.CreatedAt,
			&i.StickerName,
			&i.StickerImageUrl,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReactionsForEntity = `-- name: GetUserReactionsForEntity :many
SELECT r.id, r.sticker_id
FROM reactions r
WHERE r.entity_type = $1 AND r.entity_id = $2 AND r.user_id = $3
`

type GetUserReactionsForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	UserID     int32  `json:"user_id"`
}

type GetUserReactionsForEntityRow struct {
	ID        int64 `json:"id"`
	StickerID int64 `json:"sticker_id"`
}

func (q *Queries) GetUserReactionsForEntity(ctx context.Context, arg GetUserReactionsForEntityParams) ([]GetUserReactionsForEntityRow, error) {
	rows, err := q.db.Query(ctx, getUserReactionsForEntity, arg.EntityType, arg.EntityID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserReactionsForEntityRow{}
	for rows.Next() {
		var i GetUserReactionsForEntityRow
		if err := rows.Scan(&i.ID, &i.StickerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
