// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verdicts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearVerdictRating = `-- name: ClearVerdictRating :exec
UPDATE verdicts
SET rating = NULL, review = NULL, updated_at = now()
WHERE turn_id = $1 AND user_id = $2
`

type ClearVerdictRatingParams struct {
	TurnID int64 `json:"turn_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) ClearVerdictRating(ctx context.Context, arg ClearVerdictRatingParams) error {
	_, err := q.db.Exec(ctx, clearVerdictRating, arg.TurnID, arg.UserID)
	return err
}

const deleteVerdict = `-- name: DeleteVerdict :exec
DELETE FROM verdicts
WHERE turn_id = $1 AND user_id = $2
`

type DeleteVerdictParams struct {
	TurnID int64 `json:"turn_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteVerdict(ctx context.Context, arg DeleteVerdictParams) error {
	_, err := q.db.Exec(ctx, deleteVerdict, arg.TurnID, arg.UserID)
	return err
}

const getVerdict = `-- name: GetVerdict :one
SELECT id, turn_id, user_id, watched, rating, review, created_at, updated_at
FROM verdicts
WHERE turn_id = $1 AND user_id = $2
`

type GetVerdictParams struct {
	TurnID int64 `json:"turn_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetVerdict(ctx context.Context, arg GetVerdictParams) (Verdict, error) {
	row := q.db.QueryRow(ctx, getVerdict, arg.TurnID, arg.UserID)
	var i Verdict
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.UserID,
		&i.Watched,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerdictByID = `-- name: GetVerdictByID :one
SELECT id, turn_id, user_id, watched, rating, review, created_at, updated_at
FROM verdicts
WHERE id = $1
`

func (q *Queries) GetVerdictByID(ctx context.Context, id int64) (Verdict, error) {
	row := q.db.QueryRow(ctx, getVerdictByID, id)
	var i Verdict
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.UserID,
		&i.Watched,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerdictsForTurn = `-- name: GetVerdictsForTurn :many
SELECT v.id, v.turn_id, v.user_id, v.watched, v.rating, v.review, v.created_at, v.updated_at,
       u.username, u.avatar_url
FROM verdicts v
JOIN users u ON u.id = v.user_id
WHERE v.turn_id = $1
ORDER BY v.created_at
`

type GetVerdictsForTurnRow struct {
	ID        int64              `json:"id"`
	TurnID    int64              `json:"turn_id"`
	UserID    int32              `json:"user_id"`
	Watched   bool               `json:"watched"`
	Rating    pgtype.Numeric     `json:"rating"`
	Review    *string            `json:"review"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Username  string             `json:"username"`
	AvatarUrl *string            `json:"avatar_url"`
}

func (q *Queries) GetVerdictsForTurn(ctx context.Context, turnID int64) ([]GetVerdictsForTurnRow, error) {
	rows, err := q.db.Query(ctx, getVerdictsForTurn, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVerdictsForTurnRow{}
	for rows.Next() {
		var i GetVerdictsForTurnRow
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.UserID,
			&i.Watched,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerdictsForUser = `-- name: GetVerdictsForUser :many
SELECT v.id, v.turn_id, v.user_id, v.watched, v.rating, v.review, v.created_at, v.updated_at
FROM verdicts v
WHERE v.user_id = $1
ORDER BY v.created_at DESC
`

func (q *Queries) GetVerdictsForUser(ctx context.Context, userID int32) ([]Verdict, error) {
	rows, err := q.db.Query(ctx, getVerdictsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verdict{}
	for rows.Next() {
		var i Verdict
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.UserID,
			&i.Watched,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVerdictRating = `-- name: UpdateVerdictRating :exec
UPDATE verdicts
SET rating = $2, review = $3, updated_at = now()
WHERE turn_id = $1 AND user_id = $4
`

type UpdateVerdictRatingParams struct {
	TurnID int64          `json:"turn_id"`
	Rating pgtype.Numeric `json:"rating"`
	Review *string        `json:"review"`
	UserID int32          `json:"user_id"`
}

func (q *Queries) UpdateVerdictRating(ctx context.Context, arg UpdateVerdictRatingParams) error {
	_, err := q.db.Exec(ctx, updateVerdictRating,
		arg.TurnID,
		arg.Rating,
		arg.Review,
		arg.UserID,
	)
	return err
}

const updateVerdictWatched = `-- name: UpdateVerdictWatched :exec
UPDATE verdicts
SET watched = $2, updated_at = now()
WHERE turn_id = $1 AND user_id = $3
`

type UpdateVerdictWatchedParams struct {
	TurnID  int64 `json:"turn_id"`
	Watched bool  `json:"watched"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) UpdateVerdictWatched(ctx context.Context, arg UpdateVerdictWatchedParams) error {
	_, err := q.db.Exec(ctx, updateVerdictWatched, arg.TurnID, arg.Watched, arg.UserID)
	return err
}

const upsertVerdict = `-- name: UpsertVerdict :one
INSERT INTO verdicts (turn_id, user_id, watched, rating, review)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT verdicts_turn_user_unique
DO UPDATE SET
    watched = EXCLUDED.watched,
    rating = EXCLUDED.rating,
    review = EXCLUDED.review,
    updated_at = now()
RETURNING id, turn_id, user_id, watched, rating, review, created_at, updated_at
`

type UpsertVerdictParams struct {
	TurnID  int64          `json:"turn_id"`
	UserID  int32          `json:"user_id"`
	Watched bool           `json:"watched"`
	Rating  pgtype.Numeric `json:"rating"`
	Review  *string        `json:"review"`
}

func (q *Queries) UpsertVerdict(ctx context.Context, arg UpsertVerdictParams) (Verdict, error) {
	row := q.db.QueryRow(ctx, upsertVerdict,
		arg.TurnID,
		arg.UserID,
		arg.Watched,
		arg.Rating,
		arg.Review,
	)
	var i Verdict
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.UserID,
		&i.Watched,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
